5-stones/huginn_acumen_product_agent

lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/acumen_product_agent.rb, lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
*  Add `contrib_type` to contributor records
*  Correct category/contributor assignment to ensure inactive records are excluded
*  Add elements to the acumenAttributes that were not included previously
=> feat(agent,query_concern): Add additional data elements

lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
isDefault is now setting to true where OnWeb_LinkOnly is 0 but is then
getting overridden to true if product isDigital is true because there
can only be one digital product.
=> bug(acumen_product_query_concern): isDefault and is_master fix

lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
get first match from array of matches and set isDefault to true
=> bug(acumen_product_query_concern): get first match from array of matches

lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
=> bug(acumen_product_query_concern): use correct field for product

lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
remove weight override from field that has incorrect weight
=> feat(acumen_product_query_concer): remove weight override

lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
=> feat(acumen_client, acumen_product_query_concer): get video urls

lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
add BO_Reason and Release date field
=> feat(acumen_product_query_concer, acumen_client): BO_Reason and Release

lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
fix issue with undifined product link
=> bug(acumen_product_query_concern): fix issue with undifined product link

lib/huginn_acumen_product_agent/acumen_product_agent.rb
=> feat(acumen_product_agent): ignore skus

lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/acumen_product_agent.rb, lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
Update the fetching logic for products to have better variant support & facilitate deleting products
synced to external systems.
https://trello.com/c/p3fqs6ns/114-asbat-delete-products-in-acumen-and-have-them-automatically-deleted-in-bigcommerce
=> feat(lib/huginn_acumen_product_agent): Update product fetcher

lib/huginn_acumen_product_agent/concerns/acumen_product_query_concern.rb
add base sku on reloaded products
=> bug(acumen_product_query_concern): add base sku on reloaded products

lib/huginn_acumen_product_agent/acumen_product_agent.rb, lib/huginn_acumen_product_agent/concerns/alternate_products_query_concern.rb
Consolidate API calls to improve agent performance/response time
https://trello.com/c/RNH9chb1/402-asbat-see-all-products-in-the-admin-panel
=> fix(acumen_product_agent): Consolidate API calls

lib/huginn_acumen_product_agent/acumen_product_agent.rb, lib/huginn_acumen_product_agent/concerns/product_categories_query_concern.rb
Fix an error in the main agent processor that occasionally caused null pointers when fetching
products
https://trello.com/c/RNH9chb1/402-asbat-see-all-products-in-the-admin-panel
=> fix(acumen_product_agent): fix nill reference

lib/huginn_acumen_product_agent/acumen_agent_error.rb, lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/concerns/inv_product_query_concern.rb
Fix an error in handling product availability. When `Disable_Web_Purchase`
is true, a proeuct should be disabled.
=> fix(concerns): Fix hadnling of product availability

lib/huginn_acumen_product_agent/acumen_product_agent.rb
=> bug(acumen_product_agent): date after bug

lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/acumen_product_agent.rb, lib/huginn_acumen_product_agent/concerns/inv_product_query_concern.rb
=> feat(acumen_client, acumen_product_agent): backorder updates

lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/concerns/inv_product_query_concern.rb
=> bug(inv_product_query_concern): inventory tracking

lib/huginn_acumen_product_agent/acumen_product_agent.rb
if not tracking inventory product availability is true.
=> bug(acumen_product_agent): if not track inventory availability is true

lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/concerns/inv_product_query_concern.rb
add consignment as field to pull from acumen
=> feat(acumen_client, inv_product_query_concern): add Consignment as field

lib/huginn_acumen_product_agent/concerns/inv_product_query_concern.rb
Fix a syntax error in the track inventory conditional
=> fix(inv_product_query_concern): Fix syntax error

lib/huginn_acumen_product_agent/acumen_client.rb, lib/huginn_acumen_product_agent/concerns/inv_product_query_concern.rb
=> feat(inv_product_query_concern): add special link field
